version: "3.9"

services:
  server:
    build: ./server
    container_name: truco-server
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  client:
    build: ./client
    container_name: truco-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:4000
    depends_on:
      - server

  redis:
    image: redis:7
    container_name: truco-redis
    ports:
      - "6379:6379"
